export default [
    {
        text: 'Getting Started',
        items: [
            { text: 'Introduction', link: '/rest-api/' },
            { text: 'Authentication', link: '/rest-api/authentication' }
        ]
    },
    {
        text: 'Extending the REST API',
        collapsed: true,
        items: [
            { text: 'Overview', link: '/rest-api/extending/' },
            { text: 'Routing', link: '/rest-api/extending/routing' },
            { text: 'Controllers', link: '/rest-api/extending/controllers' },
            { text: 'Policies & Permissions', link: '/rest-api/extending/policies' },
        ]
    },
    {
        text: 'Contacts (32)',
        collapsed: true,
        items: [
            { text: 'Get Contact <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact' },
            { text: 'Get Contact Dynamic Item View <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-dynamic-item-view' },
            { text: 'Get Contact Emails <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-emails' },
            { text: 'Get Contact External View <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-external-view' },
            { text: 'Get Contact Form Submissions <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-form-submissions' },
            { text: 'Get Contact Info Widgets <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-info-widgets' },
            { text: 'Get Contact Notes <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-notes' },
            { text: 'Get Contact Prev/Next IDs <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-prev-next-ids' },
            { text: 'Get Contact Purchase History <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-purchase-history' },
            { text: 'Get Contact Support Tickets <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-support-tickets' },
            { text: 'Get Contact Template Mock <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-template-mock' },
            { text: 'Get Contact Tracking Events <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-tracking-events' },
            { text: 'Get Contact URL Metrics <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-url-metrics' },
            { text: 'List Contacts <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/list-contacts' },
            { text: 'Search Contacts <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/search-contacts' },
            { text: 'Bulk Action Contacts <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/bulk-action-contacts' },
            { text: 'Bulk Add/Update Contacts <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/bulk-add-update-contacts' },
            { text: 'Bulk Delete Contact Notes <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/bulk-delete-contact-notes' },
            { text: 'Create Contact <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/create-contact' },
            { text: 'Create Contact Note <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/create-contact-note' },
            { text: 'Save Contact External View <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/save-contact-external-view' },
            { text: 'Send Contact Custom Email <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/send-contact-custom-email' },
            { text: 'Send Contact Double Opt-in <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/send-contact-double-optin' },
            { text: 'Sync Contact Segments <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/sync-contact-segments' },
            { text: 'Track Contact Event <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/track-contact-event' },
            { text: 'Update Contact <badge type="info">PUT</badge>', link: '/rest-api/operations/contacts/update-contact' },
            { text: 'Update Contact Note <badge type="info">PUT</badge>', link: '/rest-api/operations/contacts/update-contact-note' },
            { text: 'Update Contacts Property <badge type="info">PUT</badge>', link: '/rest-api/operations/contacts/update-contacts-property' },
            { text: 'Delete Contact <badge type="danger">DELETE</badge>', link: '/rest-api/operations/contacts/delete-contact' },
            { text: 'Delete Contact Emails <badge type="danger">DELETE</badge>', link: '/rest-api/operations/contacts/delete-contact-emails' },
            { text: 'Delete Contact Note <badge type="danger">DELETE</badge>', link: '/rest-api/operations/contacts/delete-contact-note' },
            { text: 'Delete Contacts <badge type="danger">DELETE</badge>', link: '/rest-api/operations/contacts/delete-contacts' },
        ]
    },
    {
        text: 'Tags (7)',
        collapsed: true,
        items: [
            { text: 'Get Tag <badge type="tip">GET</badge>', link: '/rest-api/operations/tags/get-tag' },
            { text: 'List Tags <badge type="tip">GET</badge>', link: '/rest-api/operations/tags/list-tags' },
            { text: 'Bulk Action Tags <badge type="warning">POST</badge>', link: '/rest-api/operations/tags/bulk-action-tags' },
            { text: 'Bulk Create Tags <badge type="warning">POST</badge>', link: '/rest-api/operations/tags/bulk-create-tags' },
            { text: 'Create Tag <badge type="warning">POST</badge>', link: '/rest-api/operations/tags/create-tag' },
            { text: 'Update Tag <badge type="info">PUT</badge>', link: '/rest-api/operations/tags/update-tag' },
            { text: 'Delete Tag <badge type="danger">DELETE</badge>', link: '/rest-api/operations/tags/delete-tag' },
        ]
    },
    {
        text: 'Lists (7)',
        collapsed: true,
        items: [
            { text: 'Get List <badge type="tip">GET</badge>', link: '/rest-api/operations/lists/get-list' },
            { text: 'List Lists <badge type="tip">GET</badge>', link: '/rest-api/operations/lists/list-lists' },
            { text: 'Bulk Action Lists <badge type="warning">POST</badge>', link: '/rest-api/operations/lists/bulk-action-lists' },
            { text: 'Bulk Create Lists <badge type="warning">POST</badge>', link: '/rest-api/operations/lists/bulk-create-lists' },
            { text: 'Create List <badge type="warning">POST</badge>', link: '/rest-api/operations/lists/create-list' },
            { text: 'Update List <badge type="info">PUT</badge>', link: '/rest-api/operations/lists/update-list' },
            { text: 'Delete List <badge type="danger">DELETE</badge>', link: '/rest-api/operations/lists/delete-list' },
        ]
    },
    {
        text: 'Companies (21)',
        collapsed: true,
        items: [
            { text: 'Get Company <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/get-company' },
            { text: 'Get Company Custom Fields <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/get-company-custom-fields' },
            { text: 'Get Company External View <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/get-company-external-view' },
            { text: 'Get Company Notes <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/get-company-notes' },
            { text: 'List Companies <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/list-companies' },
            { text: 'Search Companies <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/search-companies' },
            { text: 'Search Unattached Contacts <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/search-unattached-contacts' },
            { text: 'Attach Subscribers to Companies <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/attach-company-subscribers' },
            { text: 'Bulk Action on Companies <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/bulk-action-companies' },
            { text: 'Bulk Delete Company Notes <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/bulk-delete-company-notes' },
            { text: 'Create Company <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/create-company' },
            { text: 'Create Company Note <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/create-company-note' },
            { text: 'Detach Subscribers from Companies <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/detach-company-subscribers' },
            { text: 'Import Companies from CSV <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/import-companies-csv' },
            { text: 'Rename Company Field Group <badge type="info">PUT</badge>', link: '/rest-api/operations/companies/update-company-custom-field-group-name' },
            { text: 'Save Company Custom Fields <badge type="info">PUT</badge>', link: '/rest-api/operations/companies/save-company-custom-fields' },
            { text: 'Update Companies Property <badge type="info">PUT</badge>', link: '/rest-api/operations/companies/update-companies-property' },
            { text: 'Update Company <badge type="info">PUT</badge>', link: '/rest-api/operations/companies/update-company' },
            { text: 'Update Company Note <badge type="info">PUT</badge>', link: '/rest-api/operations/companies/update-company-note' },
            { text: 'Delete Company <badge type="danger">DELETE</badge>', link: '/rest-api/operations/companies/delete-company' },
            { text: 'Delete Company Note <badge type="danger">DELETE</badge>', link: '/rest-api/operations/companies/delete-company-note' },
        ]
    },
    {
        text: 'Custom Fields (3)',
        collapsed: true,
        items: [
            { text: 'Get Contact Custom Fields <badge type="tip">GET</badge>', link: '/rest-api/operations/custom-fields/get-contact-custom-fields' },
            { text: 'Save Contact Custom Fields <badge type="info">PUT</badge>', link: '/rest-api/operations/custom-fields/save-contact-custom-fields' },
            { text: 'Update Custom Field Group Name <badge type="info">PUT</badge>', link: '/rest-api/operations/custom-fields/update-custom-field-group-name' },
        ]
    },
    {
        text: 'Labels (4)',
        collapsed: true,
        items: [
            { text: 'List Labels <badge type="tip">GET</badge>', link: '/rest-api/operations/labels/list-labels' },
            { text: 'Create Label <badge type="warning">POST</badge>', link: '/rest-api/operations/labels/create-label' },
            { text: 'Update Label <badge type="info">PUT</badge>', link: '/rest-api/operations/labels/update-label' },
            { text: 'Delete Label <badge type="danger">DELETE</badge>', link: '/rest-api/operations/labels/delete-label' },
        ]
    },
    {
        text: 'Campaigns (32)',
        collapsed: true,
        items: [
            { text: 'Get Campaign <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign' },
            { text: 'Get Campaign Contacts by Segment <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-contacts-by-segment' },
            { text: 'Get Campaign Emails <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-emails' },
            { text: 'Get Campaign Link Report <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-link-report' },
            { text: 'Get Campaign Overview Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-overview-stats' },
            { text: 'Get Campaign Processing Stat <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-processing-stat' },
            { text: 'Get Campaign Recipients Count <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-recipients-count' },
            { text: 'Get Campaign Revenues <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-revenues' },
            { text: 'Get Campaign Share URL <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-share-url' },
            { text: 'Get Campaign Status <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-status' },
            { text: 'Get Campaign Unsubscribers <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-unsubscribers' },
            { text: 'List Campaigns <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/list-campaigns' },
            { text: 'Preview Campaign Email <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/preview-campaign-email' },
            { text: 'Bulk Action Campaigns <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/bulk-action-campaigns' },
            { text: 'Create Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/create-campaign' },
            { text: 'Draft Campaign Recipients <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/draft-campaign-recipients' },
            { text: 'Duplicate Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/duplicate-campaign' },
            { text: 'Estimate Campaign Contacts <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/estimate-campaign-contacts' },
            { text: 'Pause Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/pause-campaign' },
            { text: 'Preview Campaign Email HTML <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/preview-campaign-email-html' },
            { text: 'Resume Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/resume-campaign' },
            { text: 'Resync Campaign Revenues <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/resync-campaign-revenues' },
            { text: 'Schedule Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/schedule-campaign' },
            { text: 'Send Campaign Test Email <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/send-campaign-test-email' },
            { text: 'Un-Schedule Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/un-schedule-campaign' },
            { text: 'Update Campaign Step <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/update-campaign-step' },
            { text: 'Update Single Campaign (Simulate) <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/update-single-campaign-simulate' },
            { text: 'Update Campaign <badge type="info">PUT</badge>', link: '/rest-api/operations/campaigns/update-campaign' },
            { text: 'Update Campaign Labels <badge type="info">PUT</badge>', link: '/rest-api/operations/campaigns/update-campaign-labels' },
            { text: 'Update Campaign Title <badge type="info">PUT</badge>', link: '/rest-api/operations/campaigns/update-campaign-title' },
            { text: 'Delete Campaign <badge type="danger">DELETE</badge>', link: '/rest-api/operations/campaigns/delete-campaign' },
            { text: 'Delete Campaign Emails <badge type="danger">DELETE</badge>', link: '/rest-api/operations/campaigns/delete-campaign-emails' },
        ]
    },
    {
        text: 'Templates (12)',
        collapsed: true,
        items: [
            { text: 'Get Built-In Templates <badge type="tip">GET</badge>', link: '/rest-api/operations/templates/get-built-in-templates' },
            { text: 'Get Smart Codes <badge type="tip">GET</badge>', link: '/rest-api/operations/templates/get-smart-codes' },
            { text: 'Get Template <badge type="tip">GET</badge>', link: '/rest-api/operations/templates/get-template' },
            { text: 'List All Templates <badge type="tip">GET</badge>', link: '/rest-api/operations/templates/list-all-templates' },
            { text: 'List Templates <badge type="tip">GET</badge>', link: '/rest-api/operations/templates/list-templates' },
            { text: 'Bulk Action Templates <badge type="warning">POST</badge>', link: '/rest-api/operations/templates/bulk-action-templates' },
            { text: 'Create Template <badge type="warning">POST</badge>', link: '/rest-api/operations/templates/create-template' },
            { text: 'Duplicate Template <badge type="warning">POST</badge>', link: '/rest-api/operations/templates/duplicate-template' },
            { text: 'Get Built-In Template <badge type="warning">POST</badge>', link: '/rest-api/operations/templates/get-built-in-template' },
            { text: 'Set Global Style <badge type="warning">POST</badge>', link: '/rest-api/operations/templates/set-global-style' },
            { text: 'Update Template <badge type="info">PUT</badge>', link: '/rest-api/operations/templates/update-template' },
            { text: 'Delete Template <badge type="danger">DELETE</badge>', link: '/rest-api/operations/templates/delete-template' },
        ]
    },
    {
        text: 'Email Patterns (11)',
        collapsed: true,
        items: [
            { text: 'Get Email Pattern <badge type="tip">GET</badge>', link: '/rest-api/operations/email-patterns/get-email-pattern' },
            { text: 'List Email Patterns <badge type="tip">GET</badge>', link: '/rest-api/operations/email-patterns/list-email-patterns' },
            { text: 'List Pattern Categories <badge type="tip">GET</badge>', link: '/rest-api/operations/email-patterns/list-email-pattern-categories' },
            { text: 'List Patterns (wp_block Format) <badge type="tip">GET</badge>', link: '/rest-api/operations/email-patterns/list-email-patterns-wp-format' },
            { text: 'Bulk Action Email Patterns <badge type="warning">POST</badge>', link: '/rest-api/operations/email-patterns/bulk-action-email-patterns' },
            { text: 'Create Email Pattern <badge type="warning">POST</badge>', link: '/rest-api/operations/email-patterns/create-email-pattern' },
            { text: 'Create Pattern (wp_block Format) <badge type="warning">POST</badge>', link: '/rest-api/operations/email-patterns/create-email-pattern-wp-format' },
            { text: 'Create Pattern Category <badge type="warning">POST</badge>', link: '/rest-api/operations/email-patterns/create-email-pattern-category' },
            { text: 'Update Email Pattern <badge type="info">PUT</badge>', link: '/rest-api/operations/email-patterns/update-email-pattern' },
            { text: 'Delete Email Pattern <badge type="danger">DELETE</badge>', link: '/rest-api/operations/email-patterns/delete-email-pattern' },
            { text: 'Delete Pattern Category <badge type="danger">DELETE</badge>', link: '/rest-api/operations/email-patterns/delete-email-pattern-category' },
        ]
    },
    {
        text: 'Funnels (Automations) (33)',
        collapsed: true,
        items: [
            { text: 'Get All Funnel Activities <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-all-activities' },
            { text: 'Get Funnel <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel' },
            { text: 'Get Funnel Email Reports <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-email-reports' },
            { text: 'Get Funnel Report <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-report' },
            { text: 'Get Funnel Subscriber Reporting <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-subscriber-reporting' },
            { text: 'Get Funnel Subscribers <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-subscribers' },
            { text: 'Get Funnel Syncable Counts <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-syncable-counts' },
            { text: 'Get Funnel Templates <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-templates' },
            { text: 'Get Funnel Triggers <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-triggers' },
            { text: 'Get Subscriber Automations <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-subscriber-automations' },
            { text: 'List Funnels <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/list-funnels' },
            { text: 'Bulk Action Funnels <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/bulk-action-funnels' },
            { text: 'Clone Funnel <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/clone-funnel' },
            { text: 'Create Funnel <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/create-funnel' },
            { text: 'Create Funnel from Template <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/create-funnel-from-template' },
            { text: 'Export Automation <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/export-funnel' },
            { text: 'Force Advance Funnel Subscriber <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/force-advance-funnel-subscriber' },
            { text: 'Import Funnel <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/import-funnel' },
            { text: 'Remove Bulk Subscribers from Funnels <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/remove-funnel-bulk-subscribers' },
            { text: 'Save Email Action (Fallback) <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/save-email-action-fallback' },
            { text: 'Save Funnel Email Action <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/save-funnel-email-action' },
            { text: 'Save Funnel Sequences <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/save-funnel-sequences' },
            { text: 'Save Funnel Sequences (Fallback) <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/save-funnel-sequences-fallback' },
            { text: 'Send Test Webhook <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/send-test-webhook' },
            { text: 'Sync Funnel New Steps <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/sync-funnel-new-steps' },
            { text: 'Change Funnel Trigger <badge type="info">PUT</badge>', link: '/rest-api/operations/funnels/change-funnel-trigger' },
            { text: 'Update Funnel Labels <badge type="info">PUT</badge>', link: '/rest-api/operations/funnels/update-funnel-labels' },
            { text: 'Update Funnel Property <badge type="info">PUT</badge>', link: '/rest-api/operations/funnels/update-funnel-property' },
            { text: 'Update Funnel Sticky Note <badge type="info">PUT</badge>', link: '/rest-api/operations/funnels/update-funnel-sticky-note' },
            { text: 'Update Funnel Subscription Status <badge type="info">PUT</badge>', link: '/rest-api/operations/funnels/update-funnel-subscription-status' },
            { text: 'Update Funnel Title <badge type="info">PUT</badge>', link: '/rest-api/operations/funnels/update-funnel-title' },
            { text: 'Delete Funnel <badge type="danger">DELETE</badge>', link: '/rest-api/operations/funnels/delete-funnel' },
            { text: 'Delete Funnel Subscribers <badge type="danger">DELETE</badge>', link: '/rest-api/operations/funnels/delete-funnel-subscribers' },
        ]
    },
    {
        text: 'Reports (25)',
        collapsed: true,
        items: [
            { text: 'Automation Reports <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-automation-reports' },
            { text: 'Automation Step Report <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-automation-step-report' },
            { text: 'Campaign Options <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-campaign-options' },
            { text: 'Campaigns List Report <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-campaigns-list-report' },
            { text: 'Contacts By Country <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-contacts-by-country' },
            { text: 'Contacts By Lists <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-contacts-by-lists' },
            { text: 'Contacts By Status <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-contacts-by-status' },
            { text: 'Contacts By Tags <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-contacts-by-tags' },
            { text: 'Email Unsubscribe Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-email-unsub-stats' },
            { text: 'Get Advanced Report Providers <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-advanced-report-providers' },
            { text: 'Get Ajax Options <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-ajax-options' },
            { text: 'Get Cascade Selections <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-cascade-selections' },
            { text: 'Get Contact Growth <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-contact-growth' },
            { text: 'Get Dashboard Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-dashboard-stats' },
            { text: 'Get Email Click Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-email-click-stats' },
            { text: 'Get Email Open Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-email-open-stats' },
            { text: 'Get Email Performance <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-email-performance' },
            { text: 'Get Email Sent Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-email-sent-stats' },
            { text: 'Get Report Emails <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-report-emails' },
            { text: 'Get Report Options <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-report-options' },
            { text: 'Get Taxonomy Terms <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-taxonomy-terms' },
            { text: 'Ping Report <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/ping-report' },
            { text: 'Recent Tags <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-recent-tags' },
            { text: 'Top Campaigns <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-top-campaigns' },
            { text: 'Delete Report Emails <badge type="danger">DELETE</badge>', link: '/rest-api/operations/reports/delete-report-emails' },
        ]
    },
    {
        text: 'Webhooks (4)',
        collapsed: true,
        items: [
            { text: 'List Webhooks <badge type="tip">GET</badge>', link: '/rest-api/operations/webhooks/list-webhooks' },
            { text: 'Create Webhook <badge type="warning">POST</badge>', link: '/rest-api/operations/webhooks/create-webhook' },
            { text: 'Update Webhook <badge type="info">PUT</badge>', link: '/rest-api/operations/webhooks/update-webhook' },
            { text: 'Delete Webhook <badge type="danger">DELETE</badge>', link: '/rest-api/operations/webhooks/delete-webhook' },
        ]
    },
    {
        text: 'Forms (5)',
        collapsed: true,
        items: [
            { text: 'Get Form Entries <badge type="tip">GET</badge>', link: '/rest-api/operations/forms/get-form-entries' },
            { text: 'Get Form Entry <badge type="tip">GET</badge>', link: '/rest-api/operations/forms/get-form-entry' },
            { text: 'Get Form Templates <badge type="tip">GET</badge>', link: '/rest-api/operations/forms/get-form-templates' },
            { text: 'List Forms <badge type="tip">GET</badge>', link: '/rest-api/operations/forms/list-forms' },
            { text: 'Create Form <badge type="warning">POST</badge>', link: '/rest-api/operations/forms/create-form' },
        ]
    },
    {
        text: 'Import (6)',
        collapsed: true,
        items: [
            { text: 'Get Import Driver Details <badge type="tip">GET</badge>', link: '/rest-api/operations/import/get-import-driver' },
            { text: 'Get Import Drivers <badge type="tip">GET</badge>', link: '/rest-api/operations/import/get-import-drivers' },
            { text: 'Import Contacts from CSV <badge type="warning">POST</badge>', link: '/rest-api/operations/import/import-csv-contacts' },
            { text: 'Import Data via Driver <badge type="warning">POST</badge>', link: '/rest-api/operations/import/import-driver-data' },
            { text: 'Import WordPress Users <badge type="warning">POST</badge>', link: '/rest-api/operations/import/import-wp-users' },
            { text: 'Upload CSV for Import <badge type="warning">POST</badge>', link: '/rest-api/operations/import/upload-csv-import' },
        ]
    },
    {
        text: 'Export (Pro) (11)',
        collapsed: true,
        items: [
            { text: 'Export Contacts (Page, GET) <badge type="tip">GET</badge>', link: '/rest-api/operations/export/export-contacts-page-get' },
            { text: 'Export Campaign Emails <badge type="warning">POST</badge>', link: '/rest-api/operations/export/export-campaign-emails' },
            { text: 'Export Companies <badge type="warning">POST</badge>', link: '/rest-api/operations/export/export-companies' },
            { text: 'Export Contact Notes <badge type="warning">POST</badge>', link: '/rest-api/operations/export/export-notes' },
            { text: 'Export Contacts (Page) <badge type="warning">POST</badge>', link: '/rest-api/operations/export/export-contacts-page' },
            { text: 'Export Dynamic Segment <badge type="warning">POST</badge>', link: '/rest-api/operations/export/export-dynamic-segments' },
            { text: 'Export Email Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/export/export-campaigns' },
            { text: 'Export Email Sequence <badge type="warning">POST</badge>', link: '/rest-api/operations/export/export-sequences' },
            { text: 'Export Email Template <badge type="warning">POST</badge>', link: '/rest-api/operations/export/export-templates' },
            { text: 'Export Messaging Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/export/export-message-campaigns' },
            { text: 'Export Recurring Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/export/export-recurring-campaigns' },
        ]
    },
    {
        text: 'Migrators (5)',
        collapsed: true,
        items: [
            { text: 'Get Migrator Drivers <badge type="tip">GET</badge>', link: '/rest-api/operations/migrators/get-migrator-drivers' },
            { text: 'Get Migrator List/Tag Mappings <badge type="tip">GET</badge>', link: '/rest-api/operations/migrators/get-migrator-list-tag-mappings' },
            { text: 'Execute Migrator Import <badge type="warning">POST</badge>', link: '/rest-api/operations/migrators/handle-migrator-import' },
            { text: 'Get Migrator Import Summary <badge type="warning">POST</badge>', link: '/rest-api/operations/migrators/get-migrator-import-summary' },
            { text: 'Verify Migrator Credential <badge type="warning">POST</badge>', link: '/rest-api/operations/migrators/verify-migrator-credential' },
        ]
    },
    {
        text: 'Abandon Carts (3)',
        collapsed: true,
        items: [
            { text: 'Get Abandon Cart Report Summary <badge type="tip">GET</badge>', link: '/rest-api/operations/abandon-carts/get-abandon-cart-report-summary' },
            { text: 'List Abandoned Carts <badge type="tip">GET</badge>', link: '/rest-api/operations/abandon-carts/list-abandoned-carts' },
            { text: 'Bulk Delete Abandoned Carts <badge type="warning">POST</badge>', link: '/rest-api/operations/abandon-carts/bulk-delete-abandoned-carts' },
        ]
    },
    {
        text: 'Users (2)',
        collapsed: true,
        items: [
            { text: 'Get WordPress User Roles <badge type="tip">GET</badge>', link: '/rest-api/operations/users/get-user-roles' },
            { text: 'List WordPress Users <badge type="tip">GET</badge>', link: '/rest-api/operations/users/list-users' },
        ]
    },
    {
        text: 'Global Search (1)',
        collapsed: true,
        items: [
            { text: 'Global Search <badge type="tip">GET</badge>', link: '/rest-api/operations/global-search/global-search' },
        ]
    },
    {
        text: 'Docs & Addons (3)',
        collapsed: true,
        items: [
            { text: 'Get Addons <badge type="tip">GET</badge>', link: '/rest-api/operations/docs/get-doc-addons' },
            { text: 'Get Doc <badge type="tip">GET</badge>', link: '/rest-api/operations/docs/get-doc' },
            { text: 'List Docs <badge type="tip">GET</badge>', link: '/rest-api/operations/docs/list-docs' },
        ]
    },
    {
        text: 'AI (7)',
        collapsed: true,
        items: [
            { text: 'Get AI Settings <badge type="tip">GET</badge>', link: '/rest-api/operations/ai/get-ai-settings' },
            { text: 'AI Contact Summary <badge type="warning">POST</badge>', link: '/rest-api/operations/ai/get-ai-contact-summary' },
            { text: 'Generate AI Content <badge type="warning">POST</badge>', link: '/rest-api/operations/ai/generate-ai-content' },
            { text: 'Generate AI Email Body <badge type="warning">POST</badge>', link: '/rest-api/operations/ai/generate-ai-email-body' },
            { text: 'List AI Models <badge type="warning">POST</badge>', link: '/rest-api/operations/ai/get-ai-models' },
            { text: 'Save AI Settings <badge type="warning">POST</badge>', link: '/rest-api/operations/ai/save-ai-settings' },
            { text: 'Test AI Connection <badge type="warning">POST</badge>', link: '/rest-api/operations/ai/test-ai-connection' },
        ]
    },
    {
        text: 'MCP (4)',
        collapsed: true,
        items: [
            { text: 'Get MCP Config Snippet <badge type="tip">GET</badge>', link: '/rest-api/operations/mcp/get-mcp-config-snippet' },
            { text: 'Get MCP Status <badge type="tip">GET</badge>', link: '/rest-api/operations/mcp/get-mcp-status' },
            { text: 'Install MCP Adapter <badge type="warning">POST</badge>', link: '/rest-api/operations/mcp/install-mcp-adapter' },
            { text: 'Toggle MCP Tools <badge type="warning">POST</badge>', link: '/rest-api/operations/mcp/toggle-mcp' },
        ]
    },
    {
        text: 'Settings (41)',
        collapsed: true,
        items: [
            { text: 'Database Index Health <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-db-index-health' },
            { text: 'Export System Logs <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/export-system-logs' },
            { text: 'Get Abandon Cart Settings <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-abandon-cart-settings' },
            { text: 'Get Auto Subscribe Settings <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-auto-subscribe-settings' },
            { text: 'Get Bounce Configs <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-bounce-configs' },
            { text: 'Get Compliance Settings <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-compliance-settings' },
            { text: 'Get Cron Status <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-cron-status' },
            { text: 'Get Double Opt-in Settings <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-double-optin-settings' },
            { text: 'Get Experiment Campaigns <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-experiment-campaigns' },
            { text: 'Get Experimental Settings <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-experimental-settings' },
            { text: 'Get Global Settings <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-settings' },
            { text: 'Get Integrations <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-integrations' },
            { text: 'Get Old Log Details <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-old-logs' },
            { text: 'Get REST API Keys <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-rest-keys' },
            { text: 'Get System Logs <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-system-logs' },
            { text: 'Test GET Request <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/test-get-request' },
            { text: 'Complete Installation Wizard <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/complete-installation' },
            { text: 'Create REST API Key <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/create-rest-key' },
            { text: 'Install Fluent Boards <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-boards' },
            { text: 'Install Fluent Booking <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-booking' },
            { text: 'Install Fluent Community <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-community' },
            { text: 'Install Fluent Forms <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-form' },
            { text: 'Install Fluent Support <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-support' },
            { text: 'Install FluentCart <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-cart' },
            { text: 'Install FluentSMTP <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-smtp' },
            { text: 'Repair Database Indexes <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/repair-db-indexes' },
            { text: 'Reset Database <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/reset-database' },
            { text: 'Run Cron Event <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/run-cron' },
            { text: 'Save Abandon Cart Settings <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/save-abandon-cart-settings' },
            { text: 'Save Auto Subscribe Settings <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/save-auto-subscribe-settings' },
            { text: 'Save Integration Settings <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/save-integration' },
            { text: 'Test POST Request <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/test-post-request' },
            { text: 'Update Compliance Settings <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/update-compliance-settings' },
            { text: 'Update Experimental Settings <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/update-experimental-settings' },
            { text: 'Save Double Opt-in Settings <badge type="info">PUT</badge>', link: '/rest-api/operations/settings/save-double-optin-settings' },
            { text: 'Save Global Settings <badge type="info">PUT</badge>', link: '/rest-api/operations/settings/save-settings' },
            { text: 'Test PUT Request <badge type="info">PUT</badge>', link: '/rest-api/operations/settings/test-put-request' },
            { text: 'Delete REST API Key <badge type="danger">DELETE</badge>', link: '/rest-api/operations/settings/delete-rest-key' },
            { text: 'Remove Old Logs <badge type="danger">DELETE</badge>', link: '/rest-api/operations/settings/remove-old-logs' },
            { text: 'Reset System Logs <badge type="danger">DELETE</badge>', link: '/rest-api/operations/settings/reset-system-logs' },
            { text: 'Test DELETE Request <badge type="danger">DELETE</badge>', link: '/rest-api/operations/settings/test-delete-request' },
        ]
    },
    {
        text: 'Sequences (Pro) (19)',
        collapsed: true,
        items: [
            { text: 'Get Sequence <badge type="tip">GET</badge>', link: '/rest-api/operations/sequences/get-sequence' },
            { text: 'Get Sequence Email <badge type="tip">GET</badge>', link: '/rest-api/operations/sequences/get-sequence-email' },
            { text: 'Get Sequence Subscribers <badge type="tip">GET</badge>', link: '/rest-api/operations/sequences/get-sequence-subscribers' },
            { text: 'Get Subscriber Sequences <badge type="tip">GET</badge>', link: '/rest-api/operations/sequences/get-subscriber-sequences' },
            { text: 'List Sequences <badge type="tip">GET</badge>', link: '/rest-api/operations/sequences/list-sequences' },
            { text: 'Add Sequence Subscribers <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/add-sequence-subscribers' },
            { text: 'Bulk Action Sequences <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/bulk-action-sequences' },
            { text: 'Create or Update Sequence Email <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/create-or-update-sequence-email' },
            { text: 'Create Sequence <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/create-sequence' },
            { text: 'Create Sequence Email <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/create-sequence-email' },
            { text: 'Duplicate Sequence <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/duplicate-sequence' },
            { text: 'Duplicate Sequence Email <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/duplicate-sequence-email' },
            { text: 'Reapply Sequence <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/reapply-sequence' },
            { text: 'Update Sequence <badge type="info">PUT</badge>', link: '/rest-api/operations/sequences/update-sequence' },
            { text: 'Update Sequence Email <badge type="info">PUT</badge>', link: '/rest-api/operations/sequences/update-sequence-email' },
            { text: 'Update Sequence Email Delay <badge type="info">PATCH</badge>', link: '/rest-api/operations/sequences/update-sequence-email-delay' },
            { text: 'Delete Sequence <badge type="danger">DELETE</badge>', link: '/rest-api/operations/sequences/delete-sequence' },
            { text: 'Delete Sequence Email <badge type="danger">DELETE</badge>', link: '/rest-api/operations/sequences/delete-sequence-email' },
            { text: 'Remove Sequence Subscribers <badge type="danger">DELETE</badge>', link: '/rest-api/operations/sequences/remove-sequence-subscribers' },
        ]
    },
    {
        text: 'Recurring Campaigns (Pro) (14)',
        collapsed: true,
        items: [
            { text: 'Get Recurring Campaign <badge type="tip">GET</badge>', link: '/rest-api/operations/recurring-campaigns/get-recurring-campaign' },
            { text: 'Get Recurring Campaign Email <badge type="tip">GET</badge>', link: '/rest-api/operations/recurring-campaigns/get-recurring-campaign-email' },
            { text: 'Get Recurring Campaign Emails <badge type="tip">GET</badge>', link: '/rest-api/operations/recurring-campaigns/get-recurring-campaign-emails' },
            { text: 'List Recurring Campaigns <badge type="tip">GET</badge>', link: '/rest-api/operations/recurring-campaigns/list-recurring-campaigns' },
            { text: 'Bulk Action Recurring Campaigns <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/bulk-action-recurring-campaigns' },
            { text: 'Change Recurring Campaign Status <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/change-recurring-campaign-status' },
            { text: 'Create Recurring Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/create-recurring-campaign' },
            { text: 'Delete Bulk Recurring Campaigns <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/delete-bulk-recurring-campaigns' },
            { text: 'Duplicate Recurring Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/duplicate-recurring-campaign' },
            { text: 'Update Recurring Campaign Email <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/update-recurring-campaign-email' },
            { text: 'Update Recurring Campaign Email Data <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/update-recurring-campaign-data' },
            { text: 'Update Recurring Campaign Settings <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/update-recurring-campaign-settings' },
            { text: 'Patch Recurring Campaign Email <badge type="info">PUT</badge>', link: '/rest-api/operations/recurring-campaigns/patch-recurring-campaign-email' },
            { text: 'Update Recurring Campaign Labels <badge type="info">PUT</badge>', link: '/rest-api/operations/recurring-campaigns/update-recurring-campaign-labels' },
        ]
    },
    {
        text: 'Dynamic Segments (Pro) (9)',
        collapsed: true,
        items: [
            { text: 'Get Dynamic Segment Custom Fields <badge type="tip">GET</badge>', link: '/rest-api/operations/dynamic-segments/get-dynamic-segment-custom-fields' },
            { text: 'Get Dynamic Segment Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/dynamic-segments/get-dynamic-segment-stats' },
            { text: 'Get Dynamic Segment Subscribers <badge type="tip">GET</badge>', link: '/rest-api/operations/dynamic-segments/get-dynamic-segment-subscribers' },
            { text: 'List Dynamic Segments <badge type="tip">GET</badge>', link: '/rest-api/operations/dynamic-segments/list-dynamic-segments' },
            { text: 'Create Dynamic Segment <badge type="warning">POST</badge>', link: '/rest-api/operations/dynamic-segments/create-dynamic-segment' },
            { text: 'Duplicate Dynamic Segment <badge type="warning">POST</badge>', link: '/rest-api/operations/dynamic-segments/duplicate-dynamic-segment' },
            { text: 'Estimate Dynamic Segment Contacts <badge type="warning">POST</badge>', link: '/rest-api/operations/dynamic-segments/estimate-dynamic-segment-contacts' },
            { text: 'Update Dynamic Segment <badge type="info">PUT</badge>', link: '/rest-api/operations/dynamic-segments/update-dynamic-segment' },
            { text: 'Delete Dynamic Segment <badge type="danger">DELETE</badge>', link: '/rest-api/operations/dynamic-segments/delete-dynamic-segment' },
        ]
    },
    {
        text: 'Smart Links (Pro) (5)',
        collapsed: true,
        items: [
            { text: 'List Smart Links <badge type="tip">GET</badge>', link: '/rest-api/operations/smart-links/list-smart-links' },
            { text: 'Activate Smart Links Module <badge type="warning">POST</badge>', link: '/rest-api/operations/smart-links/activate-smart-link' },
            { text: 'Create Smart Link <badge type="warning">POST</badge>', link: '/rest-api/operations/smart-links/create-smart-link' },
            { text: 'Update Smart Link <badge type="info">PUT</badge>', link: '/rest-api/operations/smart-links/update-smart-link' },
            { text: 'Delete Smart Link <badge type="danger">DELETE</badge>', link: '/rest-api/operations/smart-links/delete-smart-link' },
        ]
    },
    {
        text: 'Campaigns Pro (7)',
        collapsed: true,
        items: [
            { text: 'Get Dynamic Post Taxonomies <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns-pro/get-dynamic-post-taxonomies' },
            { text: 'Get Dynamic Posts <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns-pro/get-dynamic-posts' },
            { text: 'Get Dynamic Products <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns-pro/get-dynamic-products' },
            { text: 'Campaign Tag Actions <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns-pro/do-campaign-tag-actions' },
            { text: 'Resend Campaign Emails <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns-pro/resend-campaign-emails' },
            { text: 'Resend Failed Emails <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns-pro/resend-failed-emails' },
            { text: 'Resend Unopened Emails <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns-pro/resend-unopened-emails' },
        ]
    },
    {
        text: 'Commerce Reports (Pro) (2)',
        collapsed: true,
        items: [
            { text: 'Get Commerce Report <badge type="tip">GET</badge>', link: '/rest-api/operations/commerce-reports/get-commerce-report' },
            { text: 'Get Commerce Reports <badge type="tip">GET</badge>', link: '/rest-api/operations/commerce-reports/get-commerce-reports' },
        ]
    },
    {
        text: 'Pro Settings (8)',
        collapsed: true,
        items: [
            { text: 'Get License Status <badge type="tip">GET</badge>', link: '/rest-api/operations/pro-settings/get-license-status' },
            { text: 'List Managers <badge type="tip">GET</badge>', link: '/rest-api/operations/pro-settings/get-managers' },
            { text: 'Add Manager <badge type="warning">POST</badge>', link: '/rest-api/operations/pro-settings/add-manager' },
            { text: 'Import Funnel <badge type="warning">POST</badge>', link: '/rest-api/operations/pro-settings/import-funnel' },
            { text: 'Save License <badge type="warning">POST</badge>', link: '/rest-api/operations/pro-settings/save-license' },
            { text: 'Update Manager <badge type="info">PUT</badge>', link: '/rest-api/operations/pro-settings/update-manager' },
            { text: 'Deactivate License <badge type="danger">DELETE</badge>', link: '/rest-api/operations/pro-settings/deactivate-license' },
            { text: 'Delete Manager <badge type="danger">DELETE</badge>', link: '/rest-api/operations/pro-settings/delete-manager' },
        ]
    },
    {
        text: 'Messaging (Pro) (12)',
        collapsed: true,
        items: [
            { text: 'Get Messaging Campaign <badge type="tip">GET</badge>', link: '/rest-api/operations/messaging/get-campaign' },
            { text: 'Get Messaging Campaign Status <badge type="tip">GET</badge>', link: '/rest-api/operations/messaging/get-campaign-status' },
            { text: 'Get Subscriber Message Logs <badge type="tip">GET</badge>', link: '/rest-api/operations/messaging/get-subscriber-message-logs' },
            { text: 'List Message Threads <badge type="tip">GET</badge>', link: '/rest-api/operations/messaging/list-message-threads' },
            { text: 'List Messaging Campaigns <badge type="tip">GET</badge>', link: '/rest-api/operations/messaging/list-campaigns' },
            { text: 'List Messaging Messages <badge type="tip">GET</badge>', link: '/rest-api/operations/messaging/list-messages' },
            { text: 'List Thread Messages <badge type="tip">GET</badge>', link: '/rest-api/operations/messaging/list-thread-messages' },
            { text: 'Create Messaging Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/messaging/create-campaign' },
            { text: 'Schedule Messaging Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/messaging/schedule-campaign' },
            { text: 'Send Subscriber SMS <badge type="warning">POST</badge>', link: '/rest-api/operations/messaging/send-subscriber-message' },
            { text: 'Send Thread Message <badge type="warning">POST</badge>', link: '/rest-api/operations/messaging/send-thread-message' },
            { text: 'Update Messaging Campaign <badge type="info">PUT</badge>', link: '/rest-api/operations/messaging/update-campaign' },
        ]
    },
    {
        text: 'WhatsApp (Pro) (4)',
        collapsed: true,
        items: [
            { text: 'Get Contact WhatsApp Messages <badge type="tip">GET</badge>', link: '/rest-api/operations/whatsapp/get-subscriber-whatsapp-messages' },
            { text: 'List Messaging Templates <badge type="tip">GET</badge>', link: '/rest-api/operations/whatsapp/list-whatsapp-templates' },
            { text: 'Create Messaging Template <badge type="warning">POST</badge>', link: '/rest-api/operations/whatsapp/create-whatsapp-template' },
            { text: 'Send WhatsApp Message to Contact <badge type="warning">POST</badge>', link: '/rest-api/operations/whatsapp/send-subscriber-whatsapp-message' },
        ]
    },
    {
        text: 'Bounce Handler (Public) (2)',
        collapsed: true,
        items: [
            { text: 'Handle Bounce Webhook <badge type="tip">ANY</badge>', link: '/rest-api/operations/public-bounce/handle-bounce' },
            { text: 'Handle Bounce Webhook (/handle/ Form) <badge type="tip">ANY</badge>', link: '/rest-api/operations/public-bounce/handle-bounce-with-handle' },
        ]
    },
]
