export default [
    {
        text: 'Getting Started',
        items: [
            { text: 'Introduction', link: '/rest-api/' },
            { text: 'Authentication', link: '/rest-api/authentication' }
        ]
    },
    {
        text: 'Contacts',
        collapsed: true,
        items: [
            { text: 'List Contacts <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/list-contacts' },
            { text: 'Create Contact <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/create-contact' },
            { text: 'Get Contact <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact' },
            { text: 'Update Contact <badge type="info">PUT</badge>', link: '/rest-api/operations/contacts/update-contact' },
            { text: 'Delete Contact <badge type="danger">DELETE</badge>', link: '/rest-api/operations/contacts/delete-contact' },
            { text: 'Delete Contacts <badge type="danger">DELETE</badge>', link: '/rest-api/operations/contacts/delete-contacts' },
            { text: 'Update Property <badge type="info">PUT</badge>', link: '/rest-api/operations/contacts/update-contacts-property' },
            { text: 'Sync Segments <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/sync-contact-segments' },
            { text: 'Bulk Actions <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/bulk-action-contacts' },
            { text: 'Bulk Add/Update <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/bulk-add-update-contacts' },
            { text: 'Prev/Next IDs <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-prev-next-ids' },
            { text: 'Search Contacts <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/search-contacts' },
            { text: 'Get Emails <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-emails' },
            { text: 'Send Custom Email <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/send-contact-custom-email' },
            { text: 'Delete Emails <badge type="danger">DELETE</badge>', link: '/rest-api/operations/contacts/delete-contact-emails' },
            { text: 'Template Mock <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-template-mock' },
            { text: 'Purchase History <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-purchase-history' },
            { text: 'Form Submissions <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-form-submissions' },
            { text: 'Support Tickets <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-support-tickets' },
            { text: 'Send Double Opt-in <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/send-contact-double-optin' },
            { text: 'Get Notes <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-notes' },
            { text: 'Create Note <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/create-contact-note' },
            { text: 'Update Note <badge type="info">PUT</badge>', link: '/rest-api/operations/contacts/update-contact-note' },
            { text: 'Delete Note <badge type="danger">DELETE</badge>', link: '/rest-api/operations/contacts/delete-contact-note' },
            { text: 'External View <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-external-view' },
            { text: 'Save External View <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/save-contact-external-view' },
            { text: 'Info Widgets <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-info-widgets' },
            { text: 'Dynamic Item View <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-dynamic-item-view' },
            { text: 'Tracking Events <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-tracking-events' },
            { text: 'Track Event <badge type="warning">POST</badge>', link: '/rest-api/operations/contacts/track-contact-event' },
            { text: 'URL Metrics <badge type="tip">GET</badge>', link: '/rest-api/operations/contacts/get-contact-url-metrics' },
        ]
    },
    {
        text: 'Tags',
        collapsed: true,
        items: [
            { text: 'List Tags <badge type="tip">GET</badge>', link: '/rest-api/operations/tags/list-tags' },
            { text: 'Create Tag <badge type="warning">POST</badge>', link: '/rest-api/operations/tags/create-tag' },
            { text: 'Get Tag <badge type="tip">GET</badge>', link: '/rest-api/operations/tags/get-tag' },
            { text: 'Update Tag <badge type="info">PUT</badge>', link: '/rest-api/operations/tags/update-tag' },
            { text: 'Delete Tag <badge type="danger">DELETE</badge>', link: '/rest-api/operations/tags/delete-tag' },
            { text: 'Bulk Action <badge type="warning">POST</badge>', link: '/rest-api/operations/tags/bulk-action-tags' },
            { text: 'Bulk Create <badge type="warning">POST</badge>', link: '/rest-api/operations/tags/bulk-create-tags' },
        ]
    },
    {
        text: 'Lists',
        collapsed: true,
        items: [
            { text: 'List Lists <badge type="tip">GET</badge>', link: '/rest-api/operations/lists/list-lists' },
            { text: 'Create List <badge type="warning">POST</badge>', link: '/rest-api/operations/lists/create-list' },
            { text: 'Get List <badge type="tip">GET</badge>', link: '/rest-api/operations/lists/get-list' },
            { text: 'Update List <badge type="info">PUT</badge>', link: '/rest-api/operations/lists/update-list' },
            { text: 'Delete List <badge type="danger">DELETE</badge>', link: '/rest-api/operations/lists/delete-list' },
            { text: 'Bulk Action <badge type="warning">POST</badge>', link: '/rest-api/operations/lists/bulk-action-lists' },
            { text: 'Bulk Create <badge type="warning">POST</badge>', link: '/rest-api/operations/lists/bulk-create-lists' },
        ]
    },
    {
        text: 'Companies',
        collapsed: true,
        items: [
            { text: 'List Companies <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/list-companies' },
            { text: 'Create Company <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/create-company' },
            { text: 'Get Company <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/get-company' },
            { text: 'Update Company <badge type="info">PUT</badge>', link: '/rest-api/operations/companies/update-company' },
            { text: 'Delete Company <badge type="danger">DELETE</badge>', link: '/rest-api/operations/companies/delete-company' },
            { text: 'Search Companies <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/search-companies' },
            { text: 'Search Unattached <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/search-unattached-contacts' },
            { text: 'Update Property <badge type="info">PUT</badge>', link: '/rest-api/operations/companies/update-companies-property' },
            { text: 'Attach Subscribers <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/attach-company-subscribers' },
            { text: 'Detach Subscribers <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/detach-company-subscribers' },
            { text: 'Bulk Action <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/bulk-action-companies' },
            { text: 'Get Notes <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/get-company-notes' },
            { text: 'Create Note <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/create-company-note' },
            { text: 'Update Note <badge type="info">PUT</badge>', link: '/rest-api/operations/companies/update-company-note' },
            { text: 'Delete Note <badge type="danger">DELETE</badge>', link: '/rest-api/operations/companies/delete-company-note' },
            { text: 'CSV Import <badge type="warning">POST</badge>', link: '/rest-api/operations/companies/import-companies-csv' },
            { text: 'Get Custom Fields <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/get-company-custom-fields' },
            { text: 'Save Custom Fields <badge type="info">PUT</badge>', link: '/rest-api/operations/companies/save-company-custom-fields' },
            { text: 'External View <badge type="tip">GET</badge>', link: '/rest-api/operations/companies/get-company-external-view' },
        ]
    },
    {
        text: 'Campaigns',
        collapsed: true,
        items: [
            { text: 'List Campaigns <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/list-campaigns' },
            { text: 'Create Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/create-campaign' },
            { text: 'Get Campaign <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign' },
            { text: 'Update Campaign <badge type="info">PUT</badge>', link: '/rest-api/operations/campaigns/update-campaign' },
            { text: 'Delete Campaign <badge type="danger">DELETE</badge>', link: '/rest-api/operations/campaigns/delete-campaign' },
            { text: 'Update Title <badge type="info">PUT</badge>', link: '/rest-api/operations/campaigns/update-campaign-title' },
            { text: 'Update Step <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/update-campaign-step' },
            { text: 'Schedule <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/schedule-campaign' },
            { text: 'Unschedule <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/un-schedule-campaign' },
            { text: 'Pause <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/pause-campaign' },
            { text: 'Resume <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/resume-campaign' },
            { text: 'Duplicate <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/duplicate-campaign' },
            { text: 'Send Test Email <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/send-campaign-test-email' },
            { text: 'Preview Email HTML <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/preview-campaign-email-html' },
            { text: 'Preview Email <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/preview-campaign-email' },
            { text: 'Estimate Contacts <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/estimate-campaign-contacts' },
            { text: 'Simulate Update <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/update-single-campaign-simulate' },
            { text: 'Draft Recipients <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/draft-campaign-recipients' },
            { text: 'Recipients Count <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-recipients-count' },
            { text: 'Get Emails <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-emails' },
            { text: 'Delete Emails <badge type="danger">DELETE</badge>', link: '/rest-api/operations/campaigns/delete-campaign-emails' },
            { text: 'Processing Stat <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-processing-stat' },
            { text: 'Share URL <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-share-url' },
            { text: 'Campaign Status <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-status' },
            { text: 'Overview Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-overview-stats' },
            { text: 'Link Report <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-link-report' },
            { text: 'Revenue Report <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-revenues' },
            { text: 'Resync Revenue <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/resync-campaign-revenues' },
            { text: 'Unsubscribers <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-unsubscribers' },
            { text: 'Contacts by Segment <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns/get-campaign-contacts-by-segment' },
            { text: 'Update Labels <badge type="info">PUT</badge>', link: '/rest-api/operations/campaigns/update-campaign-labels' },
            { text: 'Bulk Action <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns/bulk-action-campaigns' },
        ]
    },
    {
        text: 'Templates',
        collapsed: true,
        items: [
            { text: 'List Templates <badge type="tip">GET</badge>', link: '/rest-api/operations/templates/list-templates' },
            { text: 'List All Templates <badge type="tip">GET</badge>', link: '/rest-api/operations/templates/list-all-templates' },
            { text: 'Create Template <badge type="warning">POST</badge>', link: '/rest-api/operations/templates/create-template' },
            { text: 'Get Template <badge type="tip">GET</badge>', link: '/rest-api/operations/templates/get-template' },
            { text: 'Update Template <badge type="info">PUT</badge>', link: '/rest-api/operations/templates/update-template' },
            { text: 'Duplicate Template <badge type="warning">POST</badge>', link: '/rest-api/operations/templates/duplicate-template' },
            { text: 'Delete Template <badge type="danger">DELETE</badge>', link: '/rest-api/operations/templates/delete-template' },
            { text: 'Bulk Action <badge type="warning">POST</badge>', link: '/rest-api/operations/templates/bulk-action-templates' },
            { text: 'Get Smart Codes <badge type="tip">GET</badge>', link: '/rest-api/operations/templates/get-smart-codes' },
            { text: 'Set Global Style <badge type="warning">POST</badge>', link: '/rest-api/operations/templates/set-global-style' },
            { text: 'Built-in Templates <badge type="tip">GET</badge>', link: '/rest-api/operations/templates/get-built-in-templates' },
        ]
    },
    {
        text: 'Funnels (Automations)',
        collapsed: true,
        items: [
            { text: 'List Funnels <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/list-funnels' },
            { text: 'Create Funnel <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/create-funnel' },
            { text: 'Get Funnel <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel' },
            { text: 'Update Property <badge type="info">PUT</badge>', link: '/rest-api/operations/funnels/update-funnel-property' },
            { text: 'Update Title <badge type="info">PUT</badge>', link: '/rest-api/operations/funnels/update-funnel-title' },
            { text: 'Delete Funnel <badge type="danger">DELETE</badge>', link: '/rest-api/operations/funnels/delete-funnel' },
            { text: 'Clone Funnel <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/clone-funnel' },
            { text: 'Import Funnel <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/import-funnel' },
            { text: 'Get Templates <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-templates' },
            { text: 'Create from Template <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/create-funnel-from-template' },
            { text: 'Get Triggers <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-triggers' },
            { text: 'Change Trigger <badge type="info">PUT</badge>', link: '/rest-api/operations/funnels/change-funnel-trigger' },
            { text: 'Save Sequences <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/save-funnel-sequences' },
            { text: 'Save Sequences (Fallback) <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/save-funnel-sequences-fallback' },
            { text: 'Save Email Action <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/save-funnel-email-action' },
            { text: 'Save Email (Fallback) <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/save-email-action-fallback' },
            { text: 'Get Subscribers <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-subscribers' },
            { text: 'Subscriber Reporting <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-subscriber-reporting' },
            { text: 'Delete Subscribers <badge type="danger">DELETE</badge>', link: '/rest-api/operations/funnels/delete-funnel-subscribers' },
            { text: 'Remove Bulk Subscribers <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/remove-funnel-bulk-subscribers' },
            { text: 'Update Sub Status <badge type="info">PUT</badge>', link: '/rest-api/operations/funnels/update-funnel-subscription-status' },
            { text: 'Force Advance <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/force-advance-funnel-subscriber' },
            { text: 'Subscriber Automations <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-subscriber-automations' },
            { text: 'All Activities <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-all-activities' },
            { text: 'Funnel Report <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-report' },
            { text: 'Email Reports <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-email-reports' },
            { text: 'Syncable Counts <badge type="tip">GET</badge>', link: '/rest-api/operations/funnels/get-funnel-syncable-counts' },
            { text: 'Sync New Steps <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/sync-funnel-new-steps' },
            { text: 'Send Test Webhook <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/send-test-webhook' },
            { text: 'Update Labels <badge type="info">PUT</badge>', link: '/rest-api/operations/funnels/update-funnel-labels' },
            { text: 'Bulk Action <badge type="warning">POST</badge>', link: '/rest-api/operations/funnels/bulk-action-funnels' },
        ]
    },
    {
        text: 'Sequences <badge type="danger">Pro</badge>',
        collapsed: true,
        items: [
            { text: 'List Sequences <badge type="tip">GET</badge>', link: '/rest-api/operations/sequences/list-sequences' },
            { text: 'Create Sequence <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/create-sequence' },
            { text: 'Get Sequence <badge type="tip">GET</badge>', link: '/rest-api/operations/sequences/get-sequence' },
            { text: 'Update Sequence <badge type="info">PUT</badge>', link: '/rest-api/operations/sequences/update-sequence' },
            { text: 'Delete Sequence <badge type="danger">DELETE</badge>', link: '/rest-api/operations/sequences/delete-sequence' },
            { text: 'Duplicate Sequence <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/duplicate-sequence' },
            { text: 'Bulk Action <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/bulk-action-sequences' },
            { text: 'Subscriber Sequences <badge type="tip">GET</badge>', link: '/rest-api/operations/sequences/get-subscriber-sequences' },
            { text: 'Get Email <badge type="tip">GET</badge>', link: '/rest-api/operations/sequences/get-sequence-email' },
            { text: 'Create Email <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/create-sequence-email' },
            { text: 'Update Email <badge type="info">PUT</badge>', link: '/rest-api/operations/sequences/update-sequence-email' },
            { text: 'Update Email Delay <badge type="info">PATCH</badge>', link: '/rest-api/operations/sequences/update-sequence-email-delay' },
            { text: 'Delete Email <badge type="danger">DELETE</badge>', link: '/rest-api/operations/sequences/delete-sequence-email' },
            { text: 'Duplicate Email <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/duplicate-sequence-email' },
            { text: 'Create/Update Email <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/create-or-update-sequence-email' },
            { text: 'Get Subscribers <badge type="tip">GET</badge>', link: '/rest-api/operations/sequences/get-sequence-subscribers' },
            { text: 'Add Subscribers <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/add-sequence-subscribers' },
            { text: 'Remove Subscribers <badge type="danger">DELETE</badge>', link: '/rest-api/operations/sequences/remove-sequence-subscribers' },
            { text: 'Reapply Sequence <badge type="warning">POST</badge>', link: '/rest-api/operations/sequences/reapply-sequence' },
        ]
    },
    {
        text: 'Recurring Campaigns <badge type="danger">Pro</badge>',
        collapsed: true,
        items: [
            { text: 'List Campaigns <badge type="tip">GET</badge>', link: '/rest-api/operations/recurring-campaigns/list-recurring-campaigns' },
            { text: 'Create Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/create-recurring-campaign' },
            { text: 'Get Campaign <badge type="tip">GET</badge>', link: '/rest-api/operations/recurring-campaigns/get-recurring-campaign' },
            { text: 'Update Data <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/update-recurring-campaign-data' },
            { text: 'Change Status <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/change-recurring-campaign-status' },
            { text: 'Update Settings <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/update-recurring-campaign-settings' },
            { text: 'Duplicate <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/duplicate-recurring-campaign' },
            { text: 'Get Emails <badge type="tip">GET</badge>', link: '/rest-api/operations/recurring-campaigns/get-recurring-campaign-emails' },
            { text: 'Get Email <badge type="tip">GET</badge>', link: '/rest-api/operations/recurring-campaigns/get-recurring-campaign-email' },
            { text: 'Patch Email <badge type="info">PUT</badge>', link: '/rest-api/operations/recurring-campaigns/patch-recurring-campaign-email' },
            { text: 'Update Email <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/update-recurring-campaign-email' },
            { text: 'Delete Bulk <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/delete-bulk-recurring-campaigns' },
            { text: 'Bulk Action <badge type="warning">POST</badge>', link: '/rest-api/operations/recurring-campaigns/bulk-action-recurring-campaigns' },
            { text: 'Update Labels <badge type="info">PUT</badge>', link: '/rest-api/operations/recurring-campaigns/update-recurring-campaign-labels' },
        ]
    },
    {
        text: 'Dynamic Segments <badge type="danger">Pro</badge>',
        collapsed: true,
        items: [
            { text: 'List Segments <badge type="tip">GET</badge>', link: '/rest-api/operations/dynamic-segments/list-dynamic-segments' },
            { text: 'Get Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/dynamic-segments/get-dynamic-segment-stats' },
            { text: 'Create Segment <badge type="warning">POST</badge>', link: '/rest-api/operations/dynamic-segments/create-dynamic-segment' },
            { text: 'Update Segment <badge type="info">PUT</badge>', link: '/rest-api/operations/dynamic-segments/update-dynamic-segment' },
            { text: 'Delete Segment <badge type="danger">DELETE</badge>', link: '/rest-api/operations/dynamic-segments/delete-dynamic-segment' },
            { text: 'Duplicate Segment <badge type="warning">POST</badge>', link: '/rest-api/operations/dynamic-segments/duplicate-dynamic-segment' },
            { text: 'Estimate Contacts <badge type="warning">POST</badge>', link: '/rest-api/operations/dynamic-segments/estimate-dynamic-segment-contacts' },
            { text: 'Get Subscribers <badge type="tip">GET</badge>', link: '/rest-api/operations/dynamic-segments/get-dynamic-segment-subscribers' },
            { text: 'Custom Fields <badge type="tip">GET</badge>', link: '/rest-api/operations/dynamic-segments/get-dynamic-segment-custom-fields' },
        ]
    },
    {
        text: 'Custom Fields',
        collapsed: true,
        items: [
            { text: 'Get Fields <badge type="tip">GET</badge>', link: '/rest-api/operations/custom-fields/get-contact-custom-fields' },
            { text: 'Save Fields <badge type="info">PUT</badge>', link: '/rest-api/operations/custom-fields/save-contact-custom-fields' },
            { text: 'Update Group Name <badge type="info">PUT</badge>', link: '/rest-api/operations/custom-fields/update-custom-field-group-name' },
        ]
    },
    {
        text: 'Labels',
        collapsed: true,
        items: [
            { text: 'List Labels <badge type="tip">GET</badge>', link: '/rest-api/operations/labels/list-labels' },
            { text: 'Create Label <badge type="warning">POST</badge>', link: '/rest-api/operations/labels/create-label' },
            { text: 'Update Label <badge type="info">PUT</badge>', link: '/rest-api/operations/labels/update-label' },
            { text: 'Delete Label <badge type="danger">DELETE</badge>', link: '/rest-api/operations/labels/delete-label' },
        ]
    },
    {
        text: 'Webhooks',
        collapsed: true,
        items: [
            { text: 'List Webhooks <badge type="tip">GET</badge>', link: '/rest-api/operations/webhooks/list-webhooks' },
            { text: 'List SMS Webhooks <badge type="tip">GET</badge>', link: '/rest-api/operations/webhooks/list-sms-webhooks' },
            { text: 'Create Webhook <badge type="warning">POST</badge>', link: '/rest-api/operations/webhooks/create-webhook' },
            { text: 'Update Webhook <badge type="info">PUT</badge>', link: '/rest-api/operations/webhooks/update-webhook' },
            { text: 'Delete Webhook <badge type="danger">DELETE</badge>', link: '/rest-api/operations/webhooks/delete-webhook' },
        ]
    },
    {
        text: 'Reports & Dashboard',
        collapsed: true,
        items: [
            { text: 'Dashboard Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-dashboard-stats' },
            { text: 'Contact Growth <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-contact-growth' },
            { text: 'Email Sent Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-email-sent-stats' },
            { text: 'Email Open Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-email-open-stats' },
            { text: 'Email Click Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-email-click-stats' },
            { text: 'Email Performance <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-email-performance' },
            { text: 'Report Options <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-report-options' },
            { text: 'Ajax Options <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-ajax-options' },
            { text: 'Taxonomy Terms <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-taxonomy-terms' },
            { text: 'Cascade Selections <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-cascade-selections' },
            { text: 'Get Emails <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-report-emails' },
            { text: 'Delete Emails <badge type="danger">DELETE</badge>', link: '/rest-api/operations/reports/delete-report-emails' },
            { text: 'Top Campaigns <badge type="tip">GET</badge> <badge type="danger">Pro</badge>', link: '/rest-api/operations/reports/get-top-campaigns' },
            { text: 'Advanced Providers <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/get-advanced-report-providers' },
            { text: 'Ping <badge type="tip">GET</badge>', link: '/rest-api/operations/reports/ping-report' },
        ]
    },
    {
        text: 'Settings',
        collapsed: true,
        items: [
            { text: 'Get Settings <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-settings' },
            { text: 'Save Settings <badge type="info">PUT</badge>', link: '/rest-api/operations/settings/save-settings' },
            { text: 'Complete Installation <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/complete-installation' },
            { text: 'Double Opt-in (Get) <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-double-optin-settings' },
            { text: 'Double Opt-in (Save) <badge type="info">PUT</badge>', link: '/rest-api/operations/settings/save-double-optin-settings' },
            { text: 'Install FluentForm <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-form' },
            { text: 'Install FluentSMTP <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-smtp' },
            { text: 'Install FluentSupport <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-support' },
            { text: 'Install FluentBoards <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-boards' },
            { text: 'Install FluentCommunity <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-community' },
            { text: 'Install FluentCart <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-cart' },
            { text: 'Install FluentBooking <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/install-fluent-booking' },
            { text: 'Bounce Configs <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-bounce-configs' },
            { text: 'Auto Subscribe (Get) <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-auto-subscribe-settings' },
            { text: 'Auto Subscribe (Save) <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/save-auto-subscribe-settings' },
            { text: 'Test GET <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/test-get-request' },
            { text: 'Test PUT <badge type="info">PUT</badge>', link: '/rest-api/operations/settings/test-put-request' },
            { text: 'Test POST <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/test-post-request' },
            { text: 'Test DELETE <badge type="danger">DELETE</badge>', link: '/rest-api/operations/settings/test-delete-request' },
            { text: 'Reset Database <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/reset-database' },
            { text: 'Old Logs (Get) <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-old-logs' },
            { text: 'Old Logs (Remove) <badge type="danger">DELETE</badge>', link: '/rest-api/operations/settings/remove-old-logs' },
            { text: 'Cron Status <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-cron-status' },
            { text: 'Run Cron <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/run-cron' },
            { text: 'REST Keys (List) <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-rest-keys' },
            { text: 'REST Keys (Create) <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/create-rest-key' },
            { text: 'REST Keys (Delete) <badge type="danger">DELETE</badge>', link: '/rest-api/operations/settings/delete-rest-key' },
            { text: 'Integrations (Get) <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-integrations' },
            { text: 'Integrations (Save) <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/save-integration' },
            { text: 'Compliance (Get) <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-compliance-settings' },
            { text: 'Compliance (Update) <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/update-compliance-settings' },
            { text: 'Experiments (Get) <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-experimental-settings' },
            { text: 'Experiments (Update) <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/update-experimental-settings' },
            { text: 'Experiment Campaigns <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-experiment-campaigns' },
            { text: 'System Logs <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-system-logs' },
            { text: 'Reset System Logs <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/reset-system-logs' },
            { text: 'Abandon Cart (Get) <badge type="tip">GET</badge>', link: '/rest-api/operations/settings/get-abandon-cart-settings' },
            { text: 'Abandon Cart (Save) <badge type="warning">POST</badge>', link: '/rest-api/operations/settings/save-abandon-cart-settings' },
        ]
    },
    {
        text: 'Import',
        collapsed: true,
        items: [
            { text: 'Upload CSV <badge type="warning">POST</badge>', link: '/rest-api/operations/import/upload-csv-import' },
            { text: 'Import CSV <badge type="warning">POST</badge>', link: '/rest-api/operations/import/import-csv-contacts' },
            { text: 'Import WP Users <badge type="warning">POST</badge>', link: '/rest-api/operations/import/import-wp-users' },
            { text: 'Get Drivers <badge type="tip">GET</badge>', link: '/rest-api/operations/import/get-import-drivers' },
            { text: 'Get Driver <badge type="tip">GET</badge>', link: '/rest-api/operations/import/get-import-driver' },
            { text: 'Import Driver Data <badge type="warning">POST</badge>', link: '/rest-api/operations/import/import-driver-data' },
        ]
    },
    {
        text: 'Users',
        collapsed: true,
        items: [
            { text: 'List Users <badge type="tip">GET</badge>', link: '/rest-api/operations/users/list-users' },
            { text: 'Get User Roles <badge type="tip">GET</badge>', link: '/rest-api/operations/users/get-user-roles' },
        ]
    },
    {
        text: 'Forms',
        collapsed: true,
        items: [
            { text: 'List Forms <badge type="tip">GET</badge>', link: '/rest-api/operations/forms/list-forms' },
            { text: 'Create Form <badge type="warning">POST</badge>', link: '/rest-api/operations/forms/create-form' },
            { text: 'Get Templates <badge type="tip">GET</badge>', link: '/rest-api/operations/forms/get-form-templates' },
            { text: 'Get Entries <badge type="tip">GET</badge>', link: '/rest-api/operations/forms/get-form-entries' },
            { text: 'Get Entry <badge type="tip">GET</badge>', link: '/rest-api/operations/forms/get-form-entry' },
        ]
    },
    {
        text: 'Smart Links <badge type="danger">Pro</badge>',
        collapsed: true,
        items: [
            { text: 'List Smart Links <badge type="tip">GET</badge>', link: '/rest-api/operations/smart-links/list-smart-links' },
            { text: 'Create Smart Link <badge type="warning">POST</badge>', link: '/rest-api/operations/smart-links/create-smart-link' },
            { text: 'Activate <badge type="warning">POST</badge>', link: '/rest-api/operations/smart-links/activate-smart-link' },
            { text: 'Update Smart Link <badge type="info">PUT</badge>', link: '/rest-api/operations/smart-links/update-smart-link' },
            { text: 'Delete Smart Link <badge type="danger">DELETE</badge>', link: '/rest-api/operations/smart-links/delete-smart-link' },
        ]
    },
    {
        text: 'Campaigns Pro <badge type="danger">Pro</badge>',
        collapsed: true,
        items: [
            { text: 'Resend Failed <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns-pro/resend-failed-emails' },
            { text: 'Resend Unopened <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns-pro/resend-unopened-emails' },
            { text: 'Resend Emails <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns-pro/resend-campaign-emails' },
            { text: 'Tag Actions <badge type="warning">POST</badge>', link: '/rest-api/operations/campaigns-pro/do-campaign-tag-actions' },
            { text: 'Get Posts <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns-pro/get-dynamic-posts' },
            { text: 'Post Taxonomies <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns-pro/get-dynamic-post-taxonomies' },
            { text: 'Get Products <badge type="tip">GET</badge>', link: '/rest-api/operations/campaigns-pro/get-dynamic-products' },
        ]
    },
    {
        text: 'Pro Settings <badge type="danger">Pro</badge>',
        collapsed: true,
        items: [
            { text: 'License Status <badge type="tip">GET</badge>', link: '/rest-api/operations/pro-settings/get-license-status' },
            { text: 'Save License <badge type="warning">POST</badge>', link: '/rest-api/operations/pro-settings/save-license' },
            { text: 'Deactivate License <badge type="danger">DELETE</badge>', link: '/rest-api/operations/pro-settings/deactivate-license' },
            { text: 'Get Managers <badge type="tip">GET</badge>', link: '/rest-api/operations/pro-settings/get-managers' },
            { text: 'Add Manager <badge type="warning">POST</badge>', link: '/rest-api/operations/pro-settings/add-manager' },
            { text: 'Update Manager <badge type="info">PUT</badge>', link: '/rest-api/operations/pro-settings/update-manager' },
            { text: 'Delete Manager <badge type="danger">DELETE</badge>', link: '/rest-api/operations/pro-settings/delete-manager' },
            { text: 'Import Funnel <badge type="warning">POST</badge>', link: '/rest-api/operations/pro-settings/import-funnel' },
            { text: 'SMS Settings (Get) <badge type="tip">GET</badge>', link: '/rest-api/operations/pro-settings/get-sms-settings' },
            { text: 'SMS Settings (Save) <badge type="warning">POST</badge>', link: '/rest-api/operations/pro-settings/save-sms-settings' },
            { text: 'Disable SMS <badge type="warning">POST</badge>', link: '/rest-api/operations/pro-settings/disable-sms' },
        ]
    },
    {
        text: 'Commerce Reports <badge type="danger">Pro</badge>',
        collapsed: true,
        items: [
            { text: 'Get Reports <badge type="tip">GET</badge>', link: '/rest-api/operations/commerce-reports/get-commerce-reports' },
            { text: 'Get Report <badge type="tip">GET</badge>', link: '/rest-api/operations/commerce-reports/get-commerce-report' },
        ]
    },
    {
        text: 'SMS <badge type="danger">Pro</badge>',
        collapsed: true,
        items: [
            { text: 'List Campaigns <badge type="tip">GET</badge>', link: '/rest-api/operations/sms/list-sms-campaigns' },
            { text: 'Create Campaign <badge type="warning">POST</badge>', link: '/rest-api/operations/sms/create-sms-campaign' },
            { text: 'Get Campaign <badge type="tip">GET</badge>', link: '/rest-api/operations/sms/get-sms-campaign' },
            { text: 'Update Campaign <badge type="info">PUT</badge>', link: '/rest-api/operations/sms/update-sms-campaign' },
            { text: 'Delete Campaign <badge type="danger">DELETE</badge>', link: '/rest-api/operations/sms/delete-sms-campaign' },
            { text: 'Schedule <badge type="warning">POST</badge>', link: '/rest-api/operations/sms/schedule-sms-campaign' },
            { text: 'Unschedule <badge type="warning">POST</badge>', link: '/rest-api/operations/sms/unschedule-sms-campaign' },
            { text: 'Pause <badge type="warning">POST</badge>', link: '/rest-api/operations/sms/pause-sms-campaign' },
            { text: 'Resume <badge type="warning">POST</badge>', link: '/rest-api/operations/sms/resume-sms-campaign' },
            { text: 'Duplicate <badge type="warning">POST</badge>', link: '/rest-api/operations/sms/duplicate-sms-campaign' },
            { text: 'Update Labels <badge type="info">PUT</badge>', link: '/rest-api/operations/sms/update-sms-campaign-labels' },
            { text: 'Estimate Contacts <badge type="warning">POST</badge>', link: '/rest-api/operations/sms/estimate-sms-campaign-contacts' },
            { text: 'Recipients Count <badge type="tip">GET</badge>', link: '/rest-api/operations/sms/get-sms-campaign-recipients-count' },
            { text: 'Campaign Status <badge type="tip">GET</badge>', link: '/rest-api/operations/sms/get-sms-campaign-status' },
            { text: 'Get Recipients <badge type="tip">GET</badge>', link: '/rest-api/operations/sms/get-sms-campaign-recipients' },
            { text: 'Tag Actions <badge type="warning">POST</badge>', link: '/rest-api/operations/sms/do-sms-campaign-tag-actions' },
            { text: 'Processing Stat <badge type="tip">GET</badge>', link: '/rest-api/operations/sms/get-sms-campaign-processing-stat' },
            { text: 'Bulk Action <badge type="warning">POST</badge>', link: '/rest-api/operations/sms/bulk-action-sms-campaigns' },
            { text: 'Subscriber Logs <badge type="tip">GET</badge>', link: '/rest-api/operations/sms/get-subscriber-sms-logs' },
            { text: 'Send Custom SMS <badge type="warning">POST</badge>', link: '/rest-api/operations/sms/send-subscriber-custom-sms' },
            { text: 'Subscriber Stats <badge type="tip">GET</badge>', link: '/rest-api/operations/sms/get-subscriber-sms-stats' },
            { text: 'List Messages <badge type="tip">GET</badge>', link: '/rest-api/operations/sms/list-sms-messages' },
            { text: 'Delete Messages <badge type="danger">DELETE</badge>', link: '/rest-api/operations/sms/delete-sms-messages' },
            { text: 'Resend Message <badge type="warning">POST</badge>', link: '/rest-api/operations/sms/resend-sms-message' },
        ]
    },
    {
        text: 'Abandon Carts',
        collapsed: true,
        items: [
            { text: 'List Carts <badge type="tip">GET</badge>', link: '/rest-api/operations/abandon-carts/list-abandoned-carts' },
            { text: 'Bulk Delete <badge type="warning">POST</badge>', link: '/rest-api/operations/abandon-carts/bulk-delete-abandoned-carts' },
            { text: 'Report Summary <badge type="tip">GET</badge>', link: '/rest-api/operations/abandon-carts/get-abandon-cart-report-summary' },
        ]
    },
    {
        text: 'Migrators',
        collapsed: true,
        items: [
            { text: 'Get Drivers <badge type="tip">GET</badge>', link: '/rest-api/operations/migrators/get-migrator-drivers' },
            { text: 'Verify Credential <badge type="warning">POST</badge>', link: '/rest-api/operations/migrators/verify-migrator-credential' },
            { text: 'List/Tag Mappings <badge type="tip">GET</badge>', link: '/rest-api/operations/migrators/get-migrator-list-tag-mappings' },
            { text: 'Import Summary <badge type="warning">POST</badge>', link: '/rest-api/operations/migrators/get-migrator-import-summary' },
            { text: 'Handle Import <badge type="warning">POST</badge>', link: '/rest-api/operations/migrators/handle-migrator-import' },
        ]
    },
    {
        text: 'Other',
        collapsed: true,
        items: [
            { text: 'Global Search <badge type="tip">GET</badge>', link: '/rest-api/operations/global-search/global-search' },
            { text: 'List Docs <badge type="tip">GET</badge>', link: '/rest-api/operations/docs/list-docs' },
            { text: 'Get Doc <badge type="tip">GET</badge>', link: '/rest-api/operations/docs/get-doc' },
            { text: 'Get Addons <badge type="tip">GET</badge>', link: '/rest-api/operations/docs/get-doc-addons' },
            { text: 'Bounce Handler <badge type="warning">POST</badge>', link: '/rest-api/operations/public-bounce/handle-bounce-with-handle' },
            { text: 'Bounce Handler (Alt) <badge type="warning">POST</badge>', link: '/rest-api/operations/public-bounce/handle-bounce' },
        ]
    },
]
